#[versions]
#agp = "8.5.0"
#kotlin = "1.9.0"
#coreKtx = "1.15.0"
#junit = "4.13.2"
#junitVersion = "1.2.1"
#espressoCore = "3.6.1"
#lifecycleRuntimeKtx = "2.8.7"
#activityCompose = "1.10.0"
#composeBom = "2024.04.01"
#core-splashscreen = "1.0.1"
#camera-core = "1.3.0-rc01"
#camera-view = "1.3.0-rc01"
#google-barcode = "17.2.0"
#navigationRuntimeKtx = "2.8.5"
#compose-runtime-lifecycle = "2.7.0-alpha02"
#accompainst = "0.28.0"
#appcompat = "1.7.0"
#material = "1.12.0"
#activity = "1.10.0"
#constraintlayout = "2.2.0"
#playServicesAds = "22.6.0"
#guava = "30.1-android"
#navigationCompose = "2.8.6"
#accompanist = "0.31.1-alpha"
#
#[libraries]
#androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
#androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
#androidx-ui = { group = "androidx.compose.ui", name = "ui" }
#androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
#androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
#androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
#androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
#androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
#core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
#androidx-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camera-core" }
#androidx-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camera-core" }
#androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-view" }
#google-mlkit-barcode = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "google-barcode" }
#androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
#compose-runtime-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-runtime-lifecycle" }
#accompainst-permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompainst" }
#androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
#androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#google-play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
#guava = { module = "com.google.guava:guava", version.ref = "guava" }
#androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
#accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
#
#
#
#[plugins]
#android-application = { id = "com.android.application", version.ref = "agp" }
#jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[versions]
agp = "8.2.2"
kotlin = "1.9.22"
core-ktx = "1.12.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
compose-bom = "2024.02.00"
compose-compiler = "1.5.8"
camera2 = "1.3.1"
camera-view = "1.3.1"
lifecycle = "2.7.0"
mlkit-barcode-scanning = "17.2.0"
zxing = "3.5.3"
navigation-runtime-ktx = "2.7.7"
navigation-compose = "2.7.7"
accompanist-permission = "0.32.0"
appcompat = "1.6.1"
material = "1.11.0"
constraintlayout = "2.1.4"
play-services-ads = "22.6.0"
guava = "32.1.3-android"
accompanist-systemuicontroller = "0.32.0"
firebase-bom = "32.7.2"
firebase-analytics = "21.5.1"
firebase-mlkit-barcode = "17.2.0"
firebase-common-ktx = "20.4.2"
play-services-code-scanner = "16.1.0"
activity = "1.10.1"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
mlkit-barcode-scanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkit-barcode-scanning" }
zxing = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigation-runtime-ktx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
accompanist-permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist-permission" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
google-play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "play-services-ads" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebase-common-ktx" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics" }
firebase-mlkit-barcode = { group = "com.google.firebase", name = "firebase-mlkit-barcode-scanning", version.ref = "firebase-mlkit-barcode" }
play-services-code-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "play-services-code-scanner" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
